# Generated by Django 5.0.2 on 2024-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abra_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='Receiver',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
