# Generated by Django 5.0.2 on 2024-02-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abra_project', '0002_massage_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massage',
            old_name='Receiver',
            new_name='ReceiverMail',
        ),
    ]
